# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProgramacaoAplicadaGrupoX
                                 A QGIS plugin
 Solução do Grupo X
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-20
        copyright            : (C) 2023 by Grupo X
        email                : borba.philipe@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Grupo X'
__date__ = '2023-03-20'
__copyright__ = '(C) 2023 by Grupo X'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProgramacaoAplicadaGrupoX class from file ProgramacaoAplicadaGrupoX.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .programacao_aplicada_grupo_X import ProgramacaoAplicadaGrupoXPlugin
    return ProgramacaoAplicadaGrupoXPlugin()
