# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ProgramacaoAplicadaGrupoX
                                 A QGIS plugin
 Solução do Grupo 2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-20
        copyright            : (C) 2023 by Grupo 2
        email                : borba.philipe@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Grupo 2'
__date__ = '2023-03-20'
__copyright__ = '(C) 2023 by Grupo 2'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'



import pandas as pd
import geopandas as gpd

from qgis.utils import iface
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProject,
                       QgsProcessingUtils,
                       QgsVectorLayer,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterVectorLayer,
                       QgsCoordinateReferenceSystem,
                       QgsProcessingParameterRasterLayer,
                       QgsVectorFileWriter,
                       QgsCoordinateTransform,
                       QgsWkbTypes,
                       QgsGeometry,
                       QgsPointXY,
                       QgsFields,
                       QgsFeature,
                       QgsField,
                       QgsRaster,
                       QgsProcessingParameterFeatureSink
                    )


class Projeto1Solucao(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT_CSV = 'INPUT_CSV'
    INPUT_RASTER = 'INPUT_RASTER'
    OUTPUT_LAYER = 'OUTPUT_LAYER'

    def tr(self, string):
        return QCoreApplication.translate('Processando', string)

    def createInstance(self):
        return Projeto1Solucao()

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Solução do Projeto 1'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):        
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Projeto 1'
        
    def shortHelpString(self):
        return self.tr("""Esse algoritmo tem como objetivo determinar a acurácia 
                          absoluta de 6 modelos de superfície. Criando uma camada 
                          temporária com atributo erro, o qual contém o vlaor de 
                          e_z. Além disso, as camadas são carregadas de modo que 
                          sua simbologia permita analisar espacialmente a distri-
                          buição dos erros """
                       )
    
    
    def initAlgorithm(self, config=None):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(QgsProcessingParameterFile(
            self.INPUT_CSV,
            'Input CSV file',
            extension='csv'
        ))         
        self.addParameter(QgsProcessingParameterRasterLayer(
            self.INPUT_RASTER,
            'Input raster layer',
        ))
        self.addParameter(QgsProcessingParameterFeatureSink(
            self.OUTPUT_LAYER,
            'Output layer',
            type=QgsProcessing.TypeVectorPoint
        ))


      
    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
       # Get input parameters
        input_csv = self.parameterAsString(parameters, self.INPUT_CSV, context)
        input_raster = self.parameterAsRasterLayer(parameters,self.INPUT_RASTER, context)

        #Convert CSV to Shapefile
        df = pd.read_csv(input_csv)
        gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.x, df.y, df.z))
        gdf.to_file('pontos_de_controle.shp', driver='ESRI Shapefile')

        #Load Shapefile into QGIS
        layer_points_control = QgsVectorLayer('pontos_de_controle.shp', 'points', 'ogr')
        if not layer_points_control.isValid():
            raise Exception('Failed to load input layer')

        # Get the coordinate systems of the layers
        raster_crs = input_raster.crs()
        point_crs = layer_points_control.crs()

        # Create a new point layer with the same CRS as the point layer
        fields = QgsFields()
        fields.append(QgsField('x', QVariant.Double))
        fields.append(QgsField('y', QVariant.Double))
        fields.append(QgsField('erro', QVariant.Double))
        (sink,dest_id) = self.parameterAsSink(
                            parameters, 
                            self.OUTPUT_LAYER, 
                            context,
                            fields,
                            QgsWkbTypes.Point,
                            raster_crs
        )

        # get the data provider for the layer
        provider = input_raster.dataProvider()
        
        
        EMQ = 0
        counter = 0
        
        # Write the filtered points to the new layer
        for feat in layer_points_control.getFeatures():
            if input_raster.extent().contains(feat.geometry().boundingBox()):
                geom = feat.geometry()
                x, y = geom.asPoint()
                point = QgsPointXY(x,y)
                pixel_value = provider.identify(point, QgsRaster.IdentifyFormatValue).results()[1]
                z = feat.attributes()[2]
                erro = abs(z - pixel_value)
                new_feat = QgsFeature()
                new_feat.setGeometry(QgsGeometry.fromPointXY(point))
                new_feat.setAttributes([x, y, erro])
                sink.addFeature(new_feat)
                EMQ = EMQ + erro**2
                counter = counter + 1
        EMQ = (EMQ/counter)**1/2
        
        feedback.pushInfo(f"EMQ = {EMQ}")

        A_EP = 1.67
        B_EP = 3.33
        C_EP = 4.0
        D_EP = 5.0

        if (EMQ < A_EP):
            feedback.pushInfo("A classe é a A")

        elif (A_EP < EMQ < B_EP):
            feedback.pushInfo("A classe é a B")
            
        elif (B_EP <EMQ < C_EP):
            feedback.pushInfo("A classe é a C")

        elif (C_EP < EMQ < D_EP):
            feedback.pushInfo("A classe é a D")

        else:
            feedback.pushInfo("Não conforme")
            
        # Compute the number of steps to display within the progress bar and
        # get features from source
        #total = 100.0 / input_raster.featureCount() if input_raster.featureCount() else 0
        #features = input_raster.getFeatures()

        #for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
        #    if feedback.isCanceled():
        #        break

            # Update the progress bar
        #    feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.

        return {self.OUTPUT_LAYER: dest_id} 